name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: docker/setup-qemu-action@v1
  
    - uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ssouthcity/failsafe:latest,ssouthcity/failsafe:${{ github.sha }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}

    - name: Save kubeconfig
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 main-cluster

    - name: Set Context
      uses: azure/k8s-set-context@v2

    - name: Create secrets
      uses: azure/k8s-create-secret@v2
      with:
        namespace: failsafe
        secret-type: generic
        secret-name: failsafe-secrets-2
        data:  ${{ secrets.FAILSAFE_SECRETS }}

    - name: Update deployment
      run: kubectl --namespace failsafe set image deployment/failsafe failsafe=ssouthcity/failsafe:${{ github.sha }}