name: Upsert Commands

on:
  push:
    branches: [ main ]
    paths: [ 'commands.json' ]

jobs:

  upsert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Upsert Commands
      run: go run cmd/failsafe-upsert-commands/main.go -token ${{ secrets.FAILSAFE_TOKEN }}